from pathlib import Path

path = Path('amysynth_version/qt_frontend/tests/integration/test_serial.py')
text = path.read_text(encoding='utf-8')
old = '''            if bool(app.query("bassRunning")):\n                start = app.bridge.count()\n                app.action("toggleBassRunning")\n                app.bridge.wait_idle(timeout=8.0)\n                lines = app.bridge.lines_since(start)\n                tags = {\n                    int(line.split(",", 2)[2][:-1])\n                    for line in lines\n                    if line.startswith("H0,0,")\n                }\n                self.assertTrue(tags)\n                self.assertTrue(all(56 <= tag < 112 for tag in tags), tags)\n                self.assertNotIn("zY0Z", lines)\n                self.assertNotIn("S4096Z", lines)\n'''
new = '''            if bool(app.query("bassRunning")):\n                start = app.bridge.count()\n                app.action("toggleBassRunning")\n                deadline = time.monotonic() + 8.0\n                tags: set[int] = set()\n                lines: list[str] = []\n                while time.monotonic() < deadline:\n                    lines = app.bridge.lines_since(start)\n                    tags = {\n                        int(line.split(",", 2)[2][:-1])\n                        for line in lines\n                        if line.startswith("H0,0,")\n                        and 56 <= int(line.split(",", 2)[2][:-1]) < 112\n                    }\n                    if tags:\n                        break\n                    time.sleep(0.01)\n                else:\n                    self.fail(\n                        "bass disable did not clear its tagged sequencer lane; received:\\n"\n                        + "\\n".join(app.bridge.lines_since(start))\n                    )\n                app.bridge.wait_idle(timeout=8.0)\n                lines = app.bridge.lines_since(start)\n                self.assertTrue(all(56 <= tag < 112 for tag in tags), tags)\n                self.assertNotIn("zY0Z", lines)\n                self.assertNotIn("S4096Z", lines)\n'''
if old not in text:
    raise SystemExit('target bass-lane test block not found')
path.write_text(text.replace(old, new, 1), encoding='utf-8')
compile(path.read_text(encoding='utf-8'), str(path), 'exec')
